java.sql.SQLNonTransientConnectionException: (conn=14253) unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:262)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
Caused by: java.sql.SQLNonTransientConnectionException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.handleIoException(AbstractQueryProtocol.java:2090)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1540)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1519)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256)
	... 11 more
Caused by: java.io.EOFException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacketArray(StandardPacketInputStream.java:249)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacket(StandardPacketInputStream.java:218)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1538)
	... 13 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:366)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:615)
	at snr.W.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:360)
	... 10 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.b(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.Z.e(Unknown Source)
	at snr.au.a(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:982)
	at snr.au.b(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 20 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.e(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.Z.e(Unknown Source)
	at snr.au.a(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:982)
	at snr.au.b(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 20 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.b(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.Z.e(Unknown Source)
	at snr.au.a(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:982)
	at snr.au.b(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 20 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.e(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.Z.e(Unknown Source)
	at snr.au.a(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:982)
	at snr.au.b(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 20 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.b(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.Z.e(Unknown Source)
	at snr.au.a(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:982)
	at snr.au.b(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 20 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.e(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.Z.e(Unknown Source)
	at snr.au.a(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:982)
	at snr.au.b(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 20 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.b(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at snr.J.l(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 19 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.e(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at snr.J.l(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 19 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.b(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at snr.J.m(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 26 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.e(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at snr.J.m(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 26 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.b(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at snr.J.m(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 26 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.e(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at snr.J.m(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 26 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.b(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at snr.J.m(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 26 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.e(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at snr.J.m(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 26 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.b(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at snr.J.m(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 26 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.e(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at snr.J.m(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 26 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.b(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at snr.J.m(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 26 more
java.sql.SQLNonTransientConnectionException: (conn=14253) (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at snr.W.e(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.W.a(Unknown Source)
	at snr.D.a(Unknown Source)
	at snr.J.a(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at snr.J.m(Unknown Source)
	at snr.J.b(Unknown Source)
	at snr.ak.<init>(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.G.a(Unknown Source)
	at snr.aj.a(Unknown Source)
	at snr.k.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.a(Unknown Source)
	at org.javelus.snr.server.SnRRestController.compileContent(Unknown Source)
	at org.javelus.snr.compile.SnRBuilder.main(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=14253) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:303)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 26 more
